export const SORT_OPTIONS = [
  { value: "last_name:asc", label: "Last Name A-Z" },
  { value: "last_name:desc", label: "Last Name Z-A" },
  { value: "first_name:asc", label: "First Name A-Z" },
  { value: "first_name:desc", label: "First Name Z-A" },
  { value: "member_id:asc", label: "Member ID Asc" },
  { value: "member_id:desc", label: "Member ID Desc" },
  { value: "level:asc", label: "Level A-Z" },
  { value: "level:desc", label: "Level Z-A" },
  { value: "employment_status:asc", label: "Employment Status A-Z" },
  { value: "employment_status:desc", label: "Employment Status Z-A" },
  { value: "gender:asc", label: "Gender A-Z" },
  { value: "gender:desc", label: "Gender Z-A" },
  { value: "date_of_birth:asc", label: "Date of Birth Oldest" },
  { value: "date_of_birth:desc", label: "Date of Birth Youngest" },
  { value: "date_of_hire:asc", label: "Date of Hire Oldest" },
  { value: "date_of_hire:desc", label: "Date of Hire Newest" },
  { value: "status:asc", label: "Status A-Z" },
  { value: "status:desc", label: "Status Z-A" },
  { value: "created_at:desc", label: "Newest First" },
  { value: "created_at:asc", label: "Oldest First" },
  { value: "updated_at:desc", label: "Recently Updated" },
  { value: "updated_at:asc", label: "Least Recently Updated" },
];
